# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"header_and_rows_to_dict": "01_cdx.ipynb",
         "mimetypes_to_regex": "01_cdx.ipynb",
         "query_wayback_cdx": "01_cdx.ipynb",
         "IA_CDX_URL": "01_cdx.ipynb",
         "CaptureIndexRecord": "01_cdx.ipynb",
         "fetch_internet_archive_content": "01_cdx.ipynb",
         "make_session": "01_cdx.ipynb",
         "WaybackResult": "01_cdx.ipynb",
         "WaybackMachine": "01_cdx.ipynb",
         "get_cc_indexes": "01_cdx.ipynb",
         "jsonl_loads": "01_cdx.ipynb",
         "query_cc_cdx_num_pages": "01_cdx.ipynb",
         "query_cc_cdx_page": "01_cdx.ipynb",
         "fetch_cc": "01_cdx.ipynb",
         "CC_DATA_URL": "01_cdx.ipynb",
         "CommonCrawl": "01_cdx.ipynb",
         "get_warc_metadata": "02_warc.ipynb",
         "QueryWARC": "02_warc.ipynb"}

modules = ["cdx.py",
           "warc.py"]

doc_url = "https://EdwardJRoss.github.io/webrefine/"

git_url = "https://github.com/EdwardJRoss/webrefine/tree/master/"

def custom_doc_links(name): return None
