# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_util.ipynb (unless otherwise specified).

__all__ = ['sha1_digest']

# Cell
from hashlib import sha1
from base64 import b32encode

def sha1_digest(content: bytes) -> str:
    return b32encode(sha1(content).digest()).decode('ascii')